spring:
  application:
    name: server-provider
---
spring:
  profiles: common
#配置分布式Session相关的配置
  data:
    mongodb:
      host: 192.168.168.168,192.168.168.169,192.168.168.170
      port: 27017
      database: app_db
      username: lizhengpeng
      password: '123456'
server:
  port: 7001
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 8
  client:
    service-url:
      defaultZone: http://127.0.0.1:7770/eureka
    refresh:
      enable: false
    fetch-registry: true
    register-with-eureka: true