spring:
  application:
    name: customer-property-server
server:
  port: 7776
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: http://127.0.0.1:7770/eureka
    eureka-server-connect-timeout-seconds: 10
    eureka-server-read-timeout-seconds: 5
    register-with-eureka: true
    fetch-registry: true